FROM alpine:3.19

RUN apk update && apk add nodejs npm git

RUN git clone https://github.com/pagefaultgames/pokerogue.git
WORKDIR /pokerogue
COPY ./tools/pokerogue.sh /pokerogue/
RUN npm install
RUN chmod +rwx ./pokerogue.sh
EXPOSE 12000

ENTRYPOINT ["./pokerogue.sh"]
